services:
  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_USER=root
      - CASSANDRA_PASSWORD=password
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./Db:/docker-entrypoint-initdb.d 
    networks:
      - cassandra_network
    command: ["bash", "-c", "docker-entrypoint.sh cassandra & sleep 90 && cqlsh -f /docker-entrypoint-initdb.d/create_db.cqlsh && tail -f /dev/null"]

volumes:
  cassandra_data:

networks:
  cassandra_network:
    driver: bridge
